#spring.application.name=banana
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##test은 사용할 database 명
#spring.datasource.url=jdbc:mysql://localhost:3306/banana?serverTimezone=Asia/Seoul
#spring.datasource.username=root
#spring.datasource.password=pass
#
##만들어진 sql 보여줌
#spring.jpa.properties.hibernate.show_sql=true
##sql 가독성 좋게 보여줌
#spring.jpa.properties.hibernate.format_sql=true
##db 초기화 전략. 기존 테이블 삭제 후 생성
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# AWS 자격 증명
spring.cloud.aws.credentials.access-key=
spring.cloud.aws.credentials.secret-key=
 
# AWS 리전
spring.cloud.aws.region.static=ap-northeast-2

# S3 엔드포인트
spring.cloud.aws.s3.endpoint=https://s3.ap-northeast-2.amazonaws.com

# S3 버킷 설정
spring.cloud.aws.s3.bucket=com.kh.cjh.bucket
spring.cloud.aws.s3.upload=upload/
spring.cloud.aws.s3.temp=temp/

spring.servlet.multipart.max-file-size=3MB

spring.datasource.url=jdbc:mariadb://localhost:[LOCAL_PORT]/kh
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=cho
spring.datasource.password=ramlethal1!

spring.ssh.tunnel.username=ec2-user
spring.ssh.tunnel.ssh-host=43.200.161.156
spring.ssh.tunnel.ssh-port=22
spring.ssh.tunnel.private-key=D:/ncs/tools/aws/myWebApi.ppk

#RDS Info
spring.ssh.tunnel.rds-host=database-1.cps40ws86g7n.ap-northeast-2.rds.amazonaws.com
spring.ssh.tunnel.rds-port=3306

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=ture