# AWS 자격 증명
spring.cloud.aws.credentials.access-key=
spring.cloud.aws.credentials.secret-key=
# AWS 리전
spring.cloud.aws.region.static=ap-northeast-2

# S3 엔드포인트
spring.cloud.aws.s3.endpoint=https://s3.ap-northeast-2.amazonaws.com

# S3 버킷 설정
spring.cloud.aws.s3.bucket=com.kh.cjh.bucket
spring.cloud.aws.s3.upload=upload/
spring.cloud.aws.s3.temp=temp/

spring.servlet.multipart.max-file-size=3MB

spring.datasource.url=jdbc:mariadb://localhost:[LOCAL_PORT]/kh
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=cho
spring.datasource.password=ramlethal1!

spring.ssh.tunnel.username=ec2-user
spring.ssh.tunnel.ssh-host=43.200.161.156
spring.ssh.tunnel.ssh-port=22
spring.ssh.tunnel.private-key=C:/AWSsetting/myWebApi.ppk

#RDS Info
spring.ssh.tunnel.rds-host=database-1.cps40ws86g7n.ap-northeast-2.rds.amazonaws.com
spring.ssh.tunnel.rds-port=3306

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=ture

#커넥선 오류 수정용 설정
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
